matches:
  # ----------------------------------------------------------------
  # VARIAVEIS GLOBAIS
  # ----------------------------------------------------------------
  - trigger: ":datahoje"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # ----------------------------------------------------------------
  # SNIPPET: Salas de Infra
  # ----------------------------------------------------------------
  - trigger: ":salasinfra"
    replace: |
      Prezados, boa tarde.

      Fizemos a verificação das salas técnicas:
      CI; SEDAP; Hall (recepção); Sicredi; Rack ASSECOM; DG; Anexo piso inferior; Anexo piso superior.

      Segue o relatório:
      ✅ Equipamentos sem sinais de alerta;
      ✅ Ar-condicionado funcionando bem;
      ✅ Salas limpas;
      ✅ Nenhuma anormalidade detectada.

      Portanto, tudo funcionando normalmente.

  # ----------------------------------------------------------------
  # EXTRAS
  # ----------------------------------------------------------------
  - trigger: ":sol"
    replace: "Sua solicitação foi atendida. Caso precise de algo mais, ficamos à disposição."

  - trigger: ":zap"
    replace: "Se não conseguir enviar pelo Teams, pode tentar enviar no nosso telefone funcional via WhatsApp: 67 98478-2034."

  - trigger: ":portal"
    replace: "sugiro realizar a abertura de um processo pelo Portal de Serviços: https://portaldeservicos.mpms.mp.br"

  # Exemplo de choice com label
  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - label: "Every moment is a fresh beginning."
              id: "bar"
            - label: "Everything you can imagine is real."
              id: "foo"
            - label: "Whatever you do, do it well."
              id: "foobar"
