# Arquivo: dicionario.ps1
# Banco de dados de correções

$global:meuDicionario = @{
    # --- SEUS ITENS PESSOAIS ---
    "mpms" = "MPMS"
    "sti" = "STI"
    "sedap" = "SEDAP"
    "paulo" = "Paulo"
    "kamila" = "Kamila"
    "ana" = "Ana"

    # --- ÓRGÃOS FEDERAIS SUPERIORES ---
    "advocacia-geral da uniao" = "Advocacia-Geral da União"
    "controladoria-geral da uniao" = "Controladoria-Geral da União"
    "defensoria publica da uniao" = "Defensoria Pública da União"
    "tribunal de contas da uniao" = "Tribunal de Contas da União"
    "ministerio publico federal" = "Ministério Público Federal"
    "supremo tribunal federal" = "Supremo Tribunal Federal"
    "superior tribunal de justica" = "Superior Tribunal de Justiça"
    "tribunal superior eleitoral" = "Tribunal Superior Eleitoral"
    "tribunal superior do trabalho" = "Tribunal Superior do Trabalho"
    "conselho nacional de justica" = "Conselho Nacional de Justiça"
    "conselho nacional do ministerio publico" = "Conselho Nacional do Ministério Público"

    # --- MINISTÉRIOS FEDERAIS (Principais) ---
    "ministerio da agricultura e pecuaria" = "Ministério da Agricultura e Pecuária"
    "ministerio da defesa" = "Ministério da Defesa"
    "ministerio da economia" = "Ministério da Economia"
    "ministerio da educacao" = "Ministério da Educação"
    "ministerio da gestao e da inovacao em servicos publicos" = "Ministério da Gestão e da Inovação em Serviços Públicos"
    "ministerio da justica e seguranca publica" = "Ministério da Justiça e Segurança Pública"
    "ministerio da saude" = "Ministério da Saúde"

    # --- TRIBUNAIS DE JUSTIÇA (ESTADOS E DF) ---
    "tribunal de justica do estado do acre" = "Tribunal de Justiça do Estado do Acre"
    "tribunal de justica do estado de alagoas" = "Tribunal de Justiça do Estado de Alagoas"
    "tribunal de justica do estado do amapa" = "Tribunal de Justiça do Estado do Amapá"
    "tribunal de justica do estado do amazonas" = "Tribunal de Justiça do Estado do Amazonas"
    "tribunal de justica do estado da bahia" = "Tribunal de Justiça do Estado da Bahia"
    "tribunal de justica do estado do ceara" = "Tribunal de Justiça do Estado do Ceará"
    "tribunal de justica do distrito federal e dos territorios" = "Tribunal de Justiça do Distrito Federal e dos Territórios"
    "tribunal de justica do estado do espirito santo" = "Tribunal de Justiça do Estado do Espírito Santo"
    "tribunal de justica do estado de goias" = "Tribunal de Justiça do Estado de Goiás"
    "tribunal de justica do estado do maranhao" = "Tribunal de Justiça do Estado do Maranhão"
    "tribunal de justica do estado de mato grosso" = "Tribunal de Justiça do Estado de Mato Grosso"
    "tribunal de justica do estado de mato grosso do sul" = "Tribunal de Justiça do Estado de Mato Grosso do Sul"
    "tribunal de justica do estado de minas gerais" = "Tribunal de Justiça do Estado de Minas Gerais"
    "tribunal de justica do estado do para" = "Tribunal de Justiça do Estado do Pará"
    "tribunal de justica do estado da paraiba" = "Tribunal de Justiça do Estado da Paraíba"
    "tribunal de justica do estado do parana" = "Tribunal de Justiça do Estado do Paraná"
    "tribunal de justica do estado de pernambuco" = "Tribunal de Justiça do Estado de Pernambuco"
    "tribunal de justica do estado do piaui" = "Tribunal de Justiça do Estado do Piauí"
    "tribunal de justica do estado do rio de janeiro" = "Tribunal de Justiça do Estado do Rio de Janeiro"
    "tribunal de justica do estado do rio grande do norte" = "Tribunal de Justiça do Estado do Rio Grande do Norte"
    "tribunal de justica do estado do rio grande do sul" = "Tribunal de Justiça do Estado do Rio Grande do Sul"
    "tribunal de justica do estado de rondonia" = "Tribunal de Justiça do Estado de Rondônia"
    "tribunal de justica do estado de roraima" = "Tribunal de Justiça do Estado de Roraima"
    "tribunal de justica do estado de santa catarina" = "Tribunal de Justiça do Estado de Santa Catarina"
    "tribunal de justica do estado de sao paulo" = "Tribunal de Justiça do Estado de São Paulo"
    "tribunal de justica do estado de sergipe" = "Tribunal de Justiça do Estado de Sergipe"
    "tribunal de justica do estado do tocantins" = "Tribunal de Justiça do Estado do Tocantins"

    # --- TRIBUNAIS REGIONAIS FEDERAIS (TRF) ---
    "tribunal regional federal da 1a regiao" = "Tribunal Regional Federal da 1ª Região"
    "tribunal regional federal da 2a regiao" = "Tribunal Regional Federal da 2ª Região"
    "tribunal regional federal da 3a regiao" = "Tribunal Regional Federal da 3ª Região"
    "tribunal regional federal da 4a regiao" = "Tribunal Regional Federal da 4ª Região"
    "tribunal regional federal da 5a regiao" = "Tribunal Regional Federal da 5ª Região"
    "tribunal regional federal da 6a regiao" = "Tribunal Regional Federal da 6ª Região"

    # --- TRIBUNAIS REGIONAIS ELEITORAIS (TRE) ---
    "tribunal regional eleitoral do acre" = "Tribunal Regional Eleitoral do Acre"
    "tribunal regional eleitoral de alagoas" = "Tribunal Regional Eleitoral de Alagoas"
    "tribunal regional eleitoral do amapa" = "Tribunal Regional Eleitoral do Amapá"
    "tribunal regional eleitoral do amazonas" = "Tribunal Regional Eleitoral do Amazonas"
    "tribunal regional eleitoral da bahia" = "Tribunal Regional Eleitoral da Bahia"
    "tribunal regional eleitoral do ceara" = "Tribunal Regional Eleitoral do Ceará"
    "tribunal regional eleitoral do distrito federal" = "Tribunal Regional Eleitoral do Distrito Federal"
    "tribunal regional eleitoral do espirito santo" = "Tribunal Regional Eleitoral do Espírito Santo"
    "tribunal regional eleitoral de goias" = "Tribunal Regional Eleitoral de Goiás"
    "tribunal regional eleitoral do maranhao" = "Tribunal Regional Eleitoral do Maranhão"
    "tribunal regional eleitoral de mato grosso" = "Tribunal Regional Eleitoral de Mato Grosso"
    "tribunal regional eleitoral de mato grosso do sul" = "Tribunal Regional Eleitoral de Mato Grosso do Sul"
    "tribunal regional eleitoral de minas gerais" = "Tribunal Regional Eleitoral de Minas Gerais"
    "tribunal regional eleitoral do para" = "Tribunal Regional Eleitoral do Pará"
    "tribunal regional eleitoral da paraiba" = "Tribunal Regional Eleitoral da Paraíba"
    "tribunal regional eleitoral do parana" = "Tribunal Regional Eleitoral do Paraná"
    "tribunal regional eleitoral de pernambuco" = "Tribunal Regional Eleitoral de Pernambuco"
    "tribunal regional eleitoral do piaui" = "Tribunal Regional Eleitoral do Piauí"
    "tribunal regional eleitoral do rio de janeiro" = "Tribunal Regional Eleitoral do Rio de Janeiro"
    "tribunal regional eleitoral do rio grande do norte" = "Tribunal Regional Eleitoral do Rio Grande do Norte"
    "tribunal regional eleitoral do rio grande do sul" = "Tribunal Regional Eleitoral do Rio Grande do Sul"
    "tribunal regional eleitoral de rondonia" = "Tribunal Regional Eleitoral de Rondônia"
    "tribunal regional eleitoral de roraima" = "Tribunal Regional Eleitoral de Roraima"
    "tribunal regional eleitoral de santa catarina" = "Tribunal Regional Eleitoral de Santa Catarina"
    "tribunal regional eleitoral de sao paulo" = "Tribunal Regional Eleitoral de São Paulo"
    "tribunal regional eleitoral de sergipe" = "Tribunal Regional Eleitoral de Sergipe"
    "tribunal regional eleitoral do tocantins" = "Tribunal Regional Eleitoral do Tocantins"

    # --- TRIBUNAIS REGIONAIS DO TRABALHO (TRT - 24 Regiões) ---
    "tribunal regional do trabalho da 1a regiao" = "Tribunal Regional do Trabalho da 1ª Região"
    "tribunal regional do trabalho da 2a regiao" = "Tribunal Regional do Trabalho da 2ª Região"
    "tribunal regional do trabalho da 3a regiao" = "Tribunal Regional do Trabalho da 3ª Região"
    "tribunal regional do trabalho da 4a regiao" = "Tribunal Regional do Trabalho da 4ª Região"
    "tribunal regional do trabalho da 5a regiao" = "Tribunal Regional do Trabalho da 5ª Região"
    "tribunal regional do trabalho da 6a regiao" = "Tribunal Regional do Trabalho da 6ª Região"
    "tribunal regional do trabalho da 7a regiao" = "Tribunal Regional do Trabalho da 7ª Região"
    "tribunal regional do trabalho da 8a regiao" = "Tribunal Regional do Trabalho da 8ª Região"
    "tribunal regional do trabalho da 9a regiao" = "Tribunal Regional do Trabalho da 9ª Região"
    "tribunal regional do trabalho da 10a regiao" = "Tribunal Regional do Trabalho da 10ª Região"
    "tribunal regional do trabalho da 11a regiao" = "Tribunal Regional do Trabalho da 11ª Região"
    "tribunal regional do trabalho da 12a regiao" = "Tribunal Regional do Trabalho da 12ª Região"
    "tribunal regional do trabalho da 13a regiao" = "Tribunal Regional do Trabalho da 13ª Região"
    "tribunal regional do trabalho da 14a regiao" = "Tribunal Regional do Trabalho da 14ª Região"
    "tribunal regional do trabalho da 15a regiao" = "Tribunal Regional do Trabalho da 15ª Região"
    "tribunal regional do trabalho da 16a regiao" = "Tribunal Regional do Trabalho da 16ª Região"
    "tribunal regional do trabalho da 17a regiao" = "Tribunal Regional do Trabalho da 17ª Região"
    "tribunal regional do trabalho da 18a regiao" = "Tribunal Regional do Trabalho da 18ª Região"
    "tribunal regional do trabalho da 19a regiao" = "Tribunal Regional do Trabalho da 19ª Região"
    "tribunal regional do trabalho da 20a regiao" = "Tribunal Regional do Trabalho da 20ª Região"
    "tribunal regional do trabalho da 21a regiao" = "Tribunal Regional do Trabalho da 21ª Região"
    "tribunal regional do trabalho da 22a regiao" = "Tribunal Regional do Trabalho da 22ª Região"
    "tribunal regional do trabalho da 23a regiao" = "Tribunal Regional do Trabalho da 23ª Região"
    "tribunal regional do trabalho da 24a regiao" = "Tribunal Regional do Trabalho da 24ª Região"

    # --- AUTARQUIAS E FORÇAS ---
    "instituto nacional do seguro social" = "Instituto Nacional do Seguro Social"
    "receita federal do brasil" = "Receita Federal do Brasil"
    "policia federal" = "Polícia Federal"
    "policia rodoviaria federal" = "Polícia Rodoviária Federal"
    "exercito brasileiro" = "Exército Brasileiro"
    "forca aerea brasileira" = "Força Aérea Brasileira"
    "marinha do brasil" = "Marinha do Brasil"

    # --- TODOS OS MINISTÉRIOS PÚBLICOS ESTADUAIS ---
    "ministerio publico do estado do acre" = "Ministério Público do Estado do Acre"
    "ministerio publico do estado de alagoas" = "Ministério Público do Estado de Alagoas"
    "ministerio publico do estado do amapa" = "Ministério Público do Estado do Amapá"
    "ministerio publico do estado do amazonas" = "Ministério Público do Estado do Amazonas"
    "ministerio publico do estado da bahia" = "Ministério Público do Estado da Bahia"
    "ministerio publico do estado do ceara" = "Ministério Público do Estado do Ceará"
    "ministerio publico do distrito federal e dos territorios" = "Ministério Público do Distrito Federal e dos Territórios"
    "ministerio publico do estado do espirito santo" = "Ministério Público do Estado do Espírito Santo"
    "ministerio publico do estado de goias" = "Ministério Público do Estado de Goiás"
    "ministerio publico do estado do maranhao" = "Ministério Público do Estado do Maranhão"
    "ministerio publico do estado de mato grosso" = "Ministério Público do Estado de Mato Grosso"
    "ministerio publico do estado de mato grosso do sul" = "Ministério Público do Estado de Mato Grosso do Sul"
    "ministerio publico do estado de minas gerais" = "Ministério Público do Estado de Minas Gerais"
    "ministerio publico do estado do para" = "Ministério Público do Estado do Pará"
    "ministerio publico do estado da paraiba" = "Ministério Público do Estado da Paraíba"
    "ministerio publico do estado do parana" = "Ministério Público do Estado do Paraná"
    "ministerio publico do estado de pernambuco" = "Ministério Público do Estado de Pernambuco"
    "ministerio publico do estado do piaui" = "Ministério Público do Estado do Piauí"
    "ministerio publico do estado do rio de janeiro" = "Ministério Público do Estado do Rio de Janeiro"
    "ministerio publico do estado do rio grande do norte" = "Ministério Público do Estado do Rio Grande do Norte"
    "ministerio publico do estado do rio grande do sul" = "Ministério Público do Estado do Rio Grande do Sul"
    "ministerio publico do estado de rondonia" = "Ministério Público do Estado de Rondônia"
    "ministerio publico do estado de roraima" = "Ministério Público do Estado de Roraima"
    "ministerio publico do estado de santa catarina" = "Ministério Público do Estado de Santa Catarina"
    "ministerio publico do estado de sao paulo" = "Ministério Público do Estado de São Paulo"
    "ministerio publico do estado de sergipe" = "Ministério Público do Estado de Sergipe"
    "ministerio publico do estado do tocantins" = "Ministério Público do Estado do Tocantins"
    "ministerio publico do trabalho" = "Ministério Público do Trabalho"
    "ministerio publico militar" = "Ministério Público Militar"

    # --- TODAS AS DEFENSORIAS PÚBLICAS ---
    "defensoria publica do distrito federal" = "Defensoria Pública do Distrito Federal"
    "defensoria publica do estado do acre" = "Defensoria Pública do Estado do Acre"
    "defensoria publica do estado de alagoas" = "Defensoria Pública do Estado de Alagoas"
    "defensoria publica do estado do amapa" = "Defensoria Pública do Estado do Amapá"
    "defensoria publica do estado do amazonas" = "Defensoria Pública do Estado do Amazonas"
    "defensoria publica do estado da bahia" = "Defensoria Pública do Estado da Bahia"
    "defensoria publica do estado do ceara" = "Defensoria Pública do Estado do Ceará"
    "defensoria publica do estado do espirito santo" = "Defensoria Pública do Estado do Espírito Santo"
    "defensoria publica do estado de goias" = "Defensoria Pública do Estado de Goiás"
    "defensoria publica do estado do maranhao" = "Defensoria Pública do Estado do Maranhão"
    "defensoria publica do estado de mato grosso" = "Defensoria Pública do Estado de Mato Grosso"
    "defensoria publica do estado de mato grosso do sul" = "Defensoria Pública do Estado de Mato Grosso do Sul"
    "defensoria publica do estado de minas gerais" = "Defensoria Pública do Estado de Minas Gerais"
    "defensoria publica do estado do para" = "Defensoria Pública do Estado do Pará"
    "defensoria publica do estado da paraiba" = "Defensoria Pública do Estado da Paraíba"
    "defensoria publica do estado do parana" = "Defensoria Pública do Estado do Paraná"
    "defensoria publica do estado de pernambuco" = "Defensoria Pública do Estado de Pernambuco"
    "defensoria publica do estado do piaui" = "Defensoria Pública do Estado do Piauí"
    "defensoria publica do estado do rio de janeiro" = "Defensoria Pública do Estado do Rio de Janeiro"
    "defensoria publica do estado do rio grande do norte" = "Defensoria Pública do Estado do Rio Grande do Norte"
    "defensoria publica do estado do rio grande do sul" = "Defensoria Pública do Estado do Rio Grande do Sul"
    "defensoria publica do estado de rondonia" = "Defensoria Pública do Estado de Rondônia"
    "defensoria publica do estado de roraima" = "Defensoria Pública do Estado de Roraima"
    "defensoria publica do estado de santa catarina" = "Defensoria Pública do Estado de Santa Catarina"
    "defensoria publica do estado de sao paulo" = "Defensoria Pública do Estado de São Paulo"
    "defensoria publica do estado de sergipe" = "Defensoria Pública do Estado de Sergipe"
    "defensoria publica do estado do tocantins" = "Defensoria Pública do Estado do Tocantins"

    # --- TODOS OS TRIBUNAIS DE CONTAS (Estados e Municípios) ---
    "tribunal de contas do distrito federal" = "Tribunal de Contas do Distrito Federal"
    "tribunal de contas do estado do acre" = "Tribunal de Contas do Estado do Acre"
    "tribunal de contas do estado de alagoas" = "Tribunal de Contas do Estado de Alagoas"
    "tribunal de contas do estado do amapa" = "Tribunal de Contas do Estado do Amapá"
    "tribunal de contas do estado do amazonas" = "Tribunal de Contas do Estado do Amazonas"
    "tribunal de contas do estado da bahia" = "Tribunal de Contas do Estado da Bahia"
    "tribunal de contas do estado do ceara" = "Tribunal de Contas do Estado do Ceará"
    "tribunal de contas do estado do espirito santo" = "Tribunal de Contas do Estado do Espírito Santo"
    "tribunal de contas do estado de goias" = "Tribunal de Contas do Estado de Goiás"
    "tribunal de contas do estado do maranhao" = "Tribunal de Contas do Estado do Maranhão"
    "tribunal de contas do estado de mato grosso" = "Tribunal de Contas do Estado de Mato Grosso"
    "tribunal de contas do estado de mato grosso do sul" = "Tribunal de Contas do Estado de Mato Grosso do Sul"
    "tribunal de contas do estado de minas gerais" = "Tribunal de Contas do Estado de Minas Gerais"
    "tribunal de contas do estado do para" = "Tribunal de Contas do Estado do Pará"
    "tribunal de contas do estado da paraiba" = "Tribunal de Contas do Estado da Paraíba"
    "tribunal de contas do estado do parana" = "Tribunal de Contas do Estado do Paraná"
    "tribunal de contas do estado de pernambuco" = "Tribunal de Contas do Estado de Pernambuco"
    "tribunal de contas do estado do piaui" = "Tribunal de Contas do Estado do Piauí"
    "tribunal de contas do estado do rio de janeiro" = "Tribunal de Contas do Estado do Rio de Janeiro"
    "tribunal de contas do estado do rio grande do norte" = "Tribunal de Contas do Estado do Rio Grande do Norte"
    "tribunal de contas do estado do rio grande do sul" = "Tribunal de Contas do Estado do Rio Grande do Sul"
    "tribunal de contas do estado de rondonia" = "Tribunal de Contas do Estado de Rondônia"
    "tribunal de contas do estado de roraima" = "Tribunal de Contas do Estado de Roraima"
    "tribunal de contas do estado de santa catarina" = "Tribunal de Contas do Estado de Santa Catarina"
    "tribunal de contas do estado de sao paulo" = "Tribunal de Contas do Estado de São Paulo"
    "tribunal de contas do estado de sergipe" = "Tribunal de Contas do Estado de Sergipe"
    "tribunal de contas do estado do tocantins" = "Tribunal de Contas do Estado do Tocantins"
    
    # --- TRIBUNAIS DE CONTAS DOS MUNICÍPIOS (TCM) ---
    "tribunal de contas dos municipios do estado da bahia" = "Tribunal de Contas dos Municípios do Estado da Bahia"
    "tribunal de contas dos municipios do estado do ceara" = "Tribunal de Contas dos Municípios do Estado do Ceará"
    "tribunal de contas dos municipios do estado de goias" = "Tribunal de Contas dos Municípios do Estado de Goiás"
    "tribunal de contas dos municipios do estado do para" = "Tribunal de Contas dos Municípios do Estado do Pará"
    "tribunal de contas do municipio de sao paulo" = "Tribunal de Contas do Município de São Paulo"
    "tribunal de contas do municipio do rio de janeiro" = "Tribunal de Contas do Município do Rio de Janeiro"

    # --- CORINGA (Se ele não achar a frase inteira do estado, arruma pelo menos a base) ---
    "tribunal de justica" = "Tribunal de Justiça"
    "tribunal regional federal" = "Tribunal Regional Federal"
    "tribunal regional eleitoral" = "Tribunal Regional Eleitoral"
    "tribunal regional do trabalho" = "Tribunal Regional do Trabalho"        
    "tribunal de contas" = "Tribunal de Contas"
    "ministerio publico" = "Ministério Público"
    "defensoria publica" = "Defensoria Pública"

}